### PR TITLE
Use precalculated factors

### PR DESCRIPTION
**Pull request by Jozo132**
Replacing `floating point division` with `floating point multiplication` for faster data processing in main loop.

### CODE REVIEW

**Comment by gabriel-milan** [comment]
Hi @Jozo132, thanks for the collaboration.

Although I enjoy the idea of this PR, if I do merge this I think I'd have an issue:

* On https://github.com/gabriel-milan/TinyMPU6050/pull/17/commits/18bd718fe5ef01c4ebd2db9927399c2a3ea17c07 you set `1 / 16384.0` as `0.00006103515` and that's accurate, but
* on https://github.com/gabriel-milan/TinyMPU6050/pull/17/commits/87c8f1ce98d4900e3e47e5de27a1e083dd92a3bd you change it from division to multiplication.

As the values are numerically equal, if you change the operation to the inverse one, results will change.

For that to work, you have either to leave the `*_TRANSFORMATION_NUMBER` as they are and change the operation to multiplication, or the opposite.

Since the whole idea is to increase data processing speed, the best thing to do is the first one. Do you wish to fix that and open a new PR?

**Comment by Jozo132** [comment]
> Hi @Jozo132, thanks for the collaboration.
> 
> Although I enjoy the idea of this PR, if I do merge this I think I'd have an issue:
> 
> * On [18bd718](https://github.com/gabriel-milan/TinyMPU6050/commit/18bd718fe5ef01c4ebd2db9927399c2a3ea17c07) you set `1 / 16384.0` as `0.00006103515` and that's accurate, but
> * on [87c8f1c](https://github.com/gabriel-milan/TinyMPU6050/commit/87c8f1ce98d4900e3e47e5de27a1e083dd92a3bd) you change it from division to multiplication.
> 
> As the values are numerically equal, if you change the operation to the inverse one, results will change.
> 
> For that to work, you have either to leave the `*_TRANSFORMATION_NUMBER` as they are and change the operation to multiplication, or the opposite.
> 
> Since the whole idea is to increase data processing speed, the best thing to do is the first one. Do you wish to fix that and open a new PR?

As you can see, the idea was to replace divisions with multiplication.
So if this abstraction holds true:
  `y = k / x      <==>      y = k * (1/x)`
that means that a constant   `z = 1/x`     simplifies all repeating divisions to multiplications
  `y = k * z`

My 'GIT' skills are terrible and I probably messed up somewhere. 
Could you please edit the changes to make it work out?

**Comment by Jozo132** [comment]
> > Hi @Jozo132, thanks for the collaboration.
> > Although I enjoy the idea of this PR, if I do merge this I think I'd have an issue:
> > 
> > * On [18bd718](https://github.com/gabriel-milan/TinyMPU6050/commit/18bd718fe5ef01c4ebd2db9927399c2a3ea17c07) you set `1 / 16384.0` as `0.00006103515` and that's accurate, but
> > * on [87c8f1c](https://github.com/gabriel-milan/TinyMPU6050/commit/87c8f1ce98d4900e3e47e5de27a1e083dd92a3bd) you change it from division to multiplication.
> > 
> > As the values are numerically equal, if you change the operation to the inverse one, results will change.
> > For that to work, you have either to leave the `*_TRANSFORMATION_NUMBER` as they are and change the operation to multiplication, or the opposite.
> > Since the whole idea is to increase data processing speed, the best thing to do is the first one. Do you wish to fix that and open a new PR?
> 
> As you can see, the idea was to replace divisions with multiplication.
> So if this abstraction holds true:
> `y = k / x <==> y = k * (1/x)`
> that means that a constant `z = 1/x` simplifies all repeating divisions to multiplications
> `y = k * z`
> 
> My 'GIT' skills are terrible and I probably messed up somewhere.
> Could you please edit the changes to make it work ou

**Comment by Jozo132** [comment]
Oops, sorry ... I thought that was the 'Close' window for the comment input

Anyway, now that I think about what you asked me. No.
It is correct. The division has to be replaced in the cpp file.
The explanation just above should be enough.

**Comment by gabriel-milan** [comment]
Omg my mistake.

When I read your PR's code, I looked on the commentaries right after your code line:

```
// (1 / 16384) precalculated
```

and assumed that `1 / 16384` was the previous value set. In that case, my first comment would make sense but yeah, you're right.

I'll merge this PR and publish a new release right after, thanks again and sorry for the misunderstanding.

**Comment by Jozo132** [comment]
@gabriel-milan I might have spotted a major issue. I have requested this pull request for each file sperately but we only merged ONE!!
When I just scrolled through your code I noticed the `divisions` were not replaced with `multiplications` but the constants were changed!

**Pull request merged**
